jobs:
- name: development
  plan:
  - get: orchestration-service
    trigger: true
  - .: (( inject meta.plan.terraform-bootstrap ))
    params:
      DEPLOY_PATH: infra
  - .: (( inject meta.plan.terraform-apply ))
    config:
      run:
        dir: 'orchestration-service/terraform/deploy/infra'
  - .: (( inject meta.plan.terraform-plan ))
    config:
      run:
        dir: 'orchestration-service/terraform/deploy/infra'
  - .: (( inject meta.plan.terraform-bootstrap ))
    params:
      DEPLOY_PATH: app
  - .: (( inject meta.plan.terraform-apply ))
    config:
      run:
        dir: 'orchestration-service/terraform/deploy/app'
  - .: (( inject meta.plan.terraform-plan ))
    config:
      run:
        dir: 'orchestration-service/terraform/deploy/app'
