jobs:
- name: integration
  plan:
  - get: dw-al2-ecs-ami
    trigger: true
    passed:
      - qa
  - get: orchestration-service
    trigger: true
    passed:
      - qa
  - .: (( inject meta.plan.terraform-bootstrap ))
    config:
      params:
        DEPLOY_PATH: app
      inputs:
          - name: dw-al2-ecs-ami
  - .: (( inject meta.plan.terraform-apply ))
    config:
      run:
        dir: 'orchestration-service/terraform/deploy/app'
    params:
      TF_WORKSPACE: integration
  - .: (( inject meta.plan.terraform-plan ))
    config:
      run:
        dir: 'orchestration-service/terraform/deploy/app'
    params:
      TF_WORKSPACE: integration

