jobs:
- name: preprod
  plan:
  - get: orchestration-service
    trigger: true
    passed:
      - qa
  - .: (( inject meta.plan.terraform-bootstrap ))
    params:
      DEPLOY_PATH: app
  - .: (( inject meta.plan.terraform-apply ))
    config:
      run:
        dir: 'orchestration-service/terraform/deploy/app'
    params:
      TF_WORKSPACE: preprod
  - .: (( inject meta.plan.terraform-plan ))
    config:
      run:
        dir: 'orchestration-service/terraform/deploy/app'
    params:
      TF_WORKSPACE: preprod
  - .: (( inject meta.plan.create-aws-profiles ))
    config:
      params:
        AWS_ACC: ((aws_account.preprod))
  - .: (( inject meta.plan.set-ecs-account-settigns ))

