jobs:
  - name: taint-dev
    plan:
      - get: orchestration-service
        trigger: false
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          DEPLOY_PATH: app

      - .: (( inject meta.plan.terraform-taint ))
        params:
          DEPLOY_PATH: app

      - .: (( inject meta.plan.terraform-apply ))
        config:
          run:
            dir: 'orchestration-service/terraform/deploy/app'
        params:
          DEPLOY_PATH: app

      - .: (( inject meta.plan.terraform-plan ))
        config:
          run:
            dir: 'orchestration-service/terraform/deploy/app'
        params:
          DEPLOY_PATH: app
