meta:
  plan:
    terraform-bootstrap:
      task: terraform-bootstrap
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: dwpdigital/jinja-yaml-aws
            tag: 0.0.19
        run:
          path: sh
          args:
            - -exc
            - |
              python bootstrap_terraform.py
              sed -i '/^assume_role/ d' terraform/deploy/$DEPLOY_PATH/terraform.tfvars
              cp terraform/deploy/$DEPLOY_PATH/terraform.tf ../terraform-config
              cp terraform/deploy/$DEPLOY_PATH/terraform.tfvars ../terraform-config
          dir: orchestration-service
        inputs:
          - name: orchestration-service
        outputs:
          - name: terraform-config
      params:
        AWS_REGION: eu-west-2

    terraform-common-config:
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ((dataworks.terraform_repository))
            tag: ((dataworks.terraform_version))
        params:
          TF_INPUT: false
          TF_CLI_ARGS_apply: -lock-timeout=300s
          TF_CLI_ARGS_plan: -lock-timeout=300s
          TF_VAR_costcode: ((dataworks.costcode))

    terraform-apply:
      task: terraform-apply
      .: (( inject meta.plan.terraform-common-config ))
      config:
        run:
          path: sh
          args:
          - -exc
          - |
            cp ../../../../terraform-config/terraform.tf .
            cp ../../../../terraform-config/terraform.tfvars .
            terraform init
            terraform workspace show
            terraform plan -out terraform.plan
            terraform apply -auto-approve terraform.plan
        inputs:
        - name: orchestration-service
        - name: terraform-config

    terraform-plan:
      task: terraform-plan
      .: (( inject meta.plan.terraform-common-config ))
      config:
        run:
          path: sh
          args:
          - -exc
          - |
            cp ../../../../terraform-config/terraform.tf .
            cp ../../../../terraform-config/terraform.tfvars .
            terraform init
            terraform workspace show
            terraform plan -detailed-exitcode
        inputs:
        - name: orchestration-service
        - name: terraform-config

    terraform-output:
      task: terraform-output
      .: (( inject meta.plan.terraform-common-config ))
      config:
        run:
          path: sh
          dir: orchestration-service/terraform/deploy
          args:
          - -exc
          - |
            cp ../../../terraform-config/terraform.tf .
            cp ../../../terraform-config/terraform.tfvars .
            terraform init
            terraform workspace show
            terraform output -json > ../../../terraform-output/outputs.json
        inputs:
        - name: orchestration-service
        - name: terraform-config
        outputs:
        - name: terraform-output
